### ISSUE TITLE
Access to whitespace between function parens and arguments

### ISSUE THREAD

**Issue by davidtheclark** [TrySound/postcss-value-parser#19]
For styelint, I need to be able to see the whitespace between function parens and arguments.

```css
a { color: rgb( 0, 0, 0    ); }
/*             ↑        ↑ */  
```

I notice that the `before` and `after` properties on a function node refer to the space before the function name and after the closing paren. I cannot find an existing property that represents the space within the parens.

Think this could be added?
