### ISSUE TITLE
parse `string` as `url` in `image-set` notation without url function

### ISSUE THREAD

**Issue by evilebottnawi** [TrySound/postcss-value-parser#43]
Example:
```css
.class {
  background-image: image-set("img1x.png" 1x, "img2x.png" 2x);
}
```
